// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {common} from '../models';
import {time} from '../models';
import {context} from '../models';

export function CloseAllChildren():Promise<void>;

export function Connect(arg1:string,arg2:number):Promise<void>;

export function Disconnect():Promise<void>;

export function GetMissionTime():Promise<string>;

export function GetTeamID():Promise<string>;

export function GetTelemetry():Promise<backend.TelemetryData>;

export function GetViewMode():Promise<string>;

export function IsConnected():Promise<boolean>;

export function IsWindowOpen(arg1:string):Promise<boolean>;

export function ListPorts():Promise<Array<string>>;

export function OpenWindow(arg1:string):Promise<void>;

export function ProcessAttitude(arg1:common.MessageAttitude):Promise<void>;

export function ProcessGpsRawInt(arg1:common.MessageGpsRawInt):Promise<void>;

export function ProcessHeartbeat(arg1:number):Promise<void>;

export function ProcessNamedValueFloat(arg1:string,arg2:number):Promise<void>;

export function ProcessScaledImu2(arg1:common.MessageScaledImu2):Promise<void>;

export function ProcessScaledPressure(arg1:common.MessageScaledPressure):Promise<void>;

export function ProcessSysStatus(arg1:common.MessageSysStatus):Promise<void>;

export function ProcessVfrHud(arg1:common.MessageVfrHud):Promise<void>;

export function ResetMPU():Promise<void>;

export function SendCommand(arg1:string):Promise<void>;

export function SetConnected(arg1:boolean):Promise<void>;

export function SetMissionStart(arg1:time.Time):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function StartupChild(arg1:context.Context):Promise<void>;

export function ToggleWindow(arg1:string):Promise<boolean>;
