// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2) {
  return window['go']['backend']['App']['Connect'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['backend']['App']['Disconnect']();
}

export function GetMissionTime() {
  return window['go']['backend']['App']['GetMissionTime']();
}

export function GetTeamID() {
  return window['go']['backend']['App']['GetTeamID']();
}

export function GetTelemetry() {
  return window['go']['backend']['App']['GetTelemetry']();
}

export function GetViewMode() {
  return window['go']['backend']['App']['GetViewMode']();
}

export function IsConnected() {
  return window['go']['backend']['App']['IsConnected']();
}

export function IsWindowOpen(arg1) {
  return window['go']['backend']['App']['IsWindowOpen'](arg1);
}

export function ListPorts() {
  return window['go']['backend']['App']['ListPorts']();
}

export function OpenWindow(arg1) {
  return window['go']['backend']['App']['OpenWindow'](arg1);
}

export function ProcessAttitude(arg1) {
  return window['go']['backend']['App']['ProcessAttitude'](arg1);
}

export function ProcessGpsRawInt(arg1) {
  return window['go']['backend']['App']['ProcessGpsRawInt'](arg1);
}

export function ProcessHeartbeat(arg1) {
  return window['go']['backend']['App']['ProcessHeartbeat'](arg1);
}

export function ProcessNamedValueFloat(arg1, arg2) {
  return window['go']['backend']['App']['ProcessNamedValueFloat'](arg1, arg2);
}

export function ProcessScaledImu2(arg1) {
  return window['go']['backend']['App']['ProcessScaledImu2'](arg1);
}

export function ProcessScaledPressure(arg1) {
  return window['go']['backend']['App']['ProcessScaledPressure'](arg1);
}

export function ProcessSysStatus(arg1) {
  return window['go']['backend']['App']['ProcessSysStatus'](arg1);
}

export function ProcessVfrHud(arg1) {
  return window['go']['backend']['App']['ProcessVfrHud'](arg1);
}

export function SendCommand(arg1) {
  return window['go']['backend']['App']['SendCommand'](arg1);
}

export function SetConnected(arg1) {
  return window['go']['backend']['App']['SetConnected'](arg1);
}

export function SetMissionStart(arg1) {
  return window['go']['backend']['App']['SetMissionStart'](arg1);
}

export function StartupChild(arg1) {
  return window['go']['backend']['App']['StartupChild'](arg1);
}

export function ToggleWindow(arg1) {
  return window['go']['backend']['App']['ToggleWindow'](arg1);
}
