// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {common} from '../models';
import {time} from '../models';

export function Connect(arg1:string,arg2:number):Promise<void>;

export function Disconnect():Promise<void>;

export function ExportGetTelemetry():Promise<backend.TelemetryData>;

export function ExportProcessAttitude(arg1:common.MessageAttitude):Promise<void>;

export function ExportProcessGpsRawInt(arg1:common.MessageGpsRawInt):Promise<void>;

export function ExportProcessHeartbeat(arg1:number):Promise<void>;

export function ExportProcessNamedValueFloat(arg1:string,arg2:number):Promise<void>;

export function ExportProcessScaledImu2(arg1:common.MessageScaledImu2):Promise<void>;

export function ExportProcessScaledPressure(arg1:common.MessageScaledPressure):Promise<void>;

export function ExportProcessSysStatus(arg1:common.MessageSysStatus):Promise<void>;

export function ExportProcessVfrHud(arg1:common.MessageVfrHud):Promise<void>;

export function ExportSetConnected(arg1:boolean):Promise<void>;

export function ExportSetMissionStart(arg1:time.Time):Promise<void>;

export function GetMissionTime():Promise<string>;

export function IsConnected():Promise<boolean>;

export function ListPorts():Promise<Array<string>>;

export function SendCommand(arg1:string):Promise<void>;
