// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2) {
  return window['go']['backend']['App']['Connect'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['backend']['App']['Disconnect']();
}

export function ExportGetTelemetry() {
  return window['go']['backend']['App']['ExportGetTelemetry']();
}

export function ExportProcessAttitude(arg1) {
  return window['go']['backend']['App']['ExportProcessAttitude'](arg1);
}

export function ExportProcessGpsRawInt(arg1) {
  return window['go']['backend']['App']['ExportProcessGpsRawInt'](arg1);
}

export function ExportProcessHeartbeat(arg1) {
  return window['go']['backend']['App']['ExportProcessHeartbeat'](arg1);
}

export function ExportProcessNamedValueFloat(arg1, arg2) {
  return window['go']['backend']['App']['ExportProcessNamedValueFloat'](arg1, arg2);
}

export function ExportProcessScaledImu2(arg1) {
  return window['go']['backend']['App']['ExportProcessScaledImu2'](arg1);
}

export function ExportProcessScaledPressure(arg1) {
  return window['go']['backend']['App']['ExportProcessScaledPressure'](arg1);
}

export function ExportProcessSysStatus(arg1) {
  return window['go']['backend']['App']['ExportProcessSysStatus'](arg1);
}

export function ExportProcessVfrHud(arg1) {
  return window['go']['backend']['App']['ExportProcessVfrHud'](arg1);
}

export function ExportSetConnected(arg1) {
  return window['go']['backend']['App']['ExportSetConnected'](arg1);
}

export function ExportSetMissionStart(arg1) {
  return window['go']['backend']['App']['ExportSetMissionStart'](arg1);
}

export function GetMissionTime() {
  return window['go']['backend']['App']['GetMissionTime']();
}

export function IsConnected() {
  return window['go']['backend']['App']['IsConnected']();
}

export function ListPorts() {
  return window['go']['backend']['App']['ListPorts']();
}

export function SendCommand(arg1) {
  return window['go']['backend']['App']['SendCommand'](arg1);
}
